echo "Please input username:"
read USERNAME
echo "Please input password"
read PASSWORD
echo "Please input DB Name"
read DATABASENAME

mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE $DATABASENAME; \
CREATE USER '$USERNAME' IDENTIFIED BY '$PASSWORD'; \
REVOKE ALL PRIVILEGES,GRANT OPTION from $USERNAME; \
GRANT USAGE ON $DATABASENAME.* to '$USERNAME'@'%' IDENTIFIED BY '$PASSWORD'; \
GRANT ALL PRIVILEGES ON $DATABASENAME.* TO '$USERNAME'@'%' WITH GRANT OPTION; \
FLUSH PRIVILEGES;"
